blawar/nut

- nut/Config.py
- nut/Titles.py
> Remove migrations

- nut.py
Importing USB would fail. Fixed the import
> Import USB fix

- Fs/Nsp.py
> Fix Title ID Parsing

- requirements.txt
This can install all required packages by doing `pip install -r requirements.txt`
> Create pip-requirements file

- requirements.txt
The condition order was inverted
> Fix requirements typo

- README.md
- requirements.txt
Changes the instructions in README.md a bit so people don't change the /etc folder on mac, which is unnecessary. 
Changed the requirements.txt so it shouldn't throw an error when not using requirements.txt on windows, which it most likely won't be used for.
Sorry if I did something wrong, I don't use GitHub for coding.
> Mac friendly-er

- .gitignore
- nut/__init__.py
- nut/nsps.py
- nut/users.py
- server/__init__.py
- server/controller/api.py
* added scanning of NSPs to the api search request to handle
new games in the games folder (fixes issue #169)
* added check for existence of games files at NSPs load (fixes issue #192)
* fixed unreachable code warning in server/controller/api.py
* added Visual Studio Code folder to .gitignore
* added hidden system MacOS folder .DS_Store to .gitignore
* removed unused variables in nut/nsps.py, server/controller/api.py and server/__init__.py
> Added scan of games in runtime and removal of non-existing games (closes #169 and #192)

- nut/config.py
- nut_gui.py
* path text changed event replaced with explicit save button action
* added method updateMainPath for config to update main path in config file
And purge NSPs list if path changed
* removed unused variable in nut_gui.py
> Purged NSPs files list on path update via GUI (closes #164)

- .travis.yml
- README.md
- requirements.txt
- tests/nut_config_test.py
* added Travis CI config file
* added some tests for config.py
> Added initial unit tests

- nut.py
- nut_gui.py
- nut_impl/__init__.py
- nut_impl/config.py
- nut_impl/nsp.py
- nut_impl/nsps.py
- nut_impl/printer.py
- nut_impl/status.py
- nut_impl/usb.py
- nut_impl/users.py
- server/__init__.py
- server/controller/api.py
- tests/nut_config_test.py
* renamed nut module folder to nut_impl to get rid
of conflict with nut.py file
> Fix 'nut' import ambiguity

- nut_gui.py
* added user friendly file size formatting for files at UI
> Added correct sorting by file size (fixes #129)

- gui/panes/files.py
- gui/table_model.py
> Fixed slow table update (fixes #215)

- tests/nut_config_test.py
* added update_scan_paths test cases
* added regionLanguages test cases
> Added more config tests

- nut/__init__.py
* reorganised imports in nut/__init__.py
> Fixed issue #254

- gui/panes/filters.py
- public_html/translate.json
* updated translations for filters pane
> Fixed issue #253

- Fs/Nsp.py
- nut/Nsps.py
* added logging for getting file size
* try to get file size for null records in files.json at file load
> Fixed issue #260

- .pylintrc
- gui/app.py
- gui/header.py
- gui/panes/dirlist.py
- gui/panes/filters.py
- gui/panes/format.py
- gui/table_model.py
- gui/tabs.py
- nut/Config.py
- public_html/translate.json
- tasks.py
* added gui/panes/dirlist.py for linting
* fixed issue with lost scanning path in the config file
* fixed tab stop for some UI controls
* used super() python 3 method for some UI controls
> Fixed issue #234

- Fs/driver/curl.py
This PR will resolve the issue #266 .
> Fixed incorrect variable in curl.py file

- conf/nut.default.conf
> Fixed Indentation

- conf/nut.default.conf
- add additional default paths
- disable local drive access by default
> nut.default.conf: update

- plugins/discord/__init__.py
Use real numbers, more descriptive footer using the real release date
> Update Discord embed

- nut/Users.py
- tests/nut_users_test.py
- removed unused method Users.save()
- added test for loading users from file
- used same encoding for opening file in Users.export() as in Users.load()
> added tests for Users.py

- gui/app.py
- gui/header.py
- gui/panes/filters.py
- gui/table_model.py
- nut/Config.py
- requirements.txt
- tasks.py
- tests/nut_config_test.py
- used humanize lib for formatting sizes
- added gui/table_model.py to linting
> improved linting

- gui/panes/options.py
- tasks.py
- added gui/panes/options.py to lint check
> fixed linting

- gui/panes/options.py
- tasks.py
- tests-gui/gui_app_test.py
- fixed coverage calculation in CI
- added gui test for options tab
- refactored options.py
> refactoring

- gui/panes/filters.py
- public_html/translate.json
> gui filters refactoring

- nut.py
Code works fine without cdn, so forcing exception is unneeded.
> no cdn -> no exception
